name: tg-bot-admin

services:
  postgres:
    image: postgres:18.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-tgadmin}
    #ports:
    #  - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ..
      dockerfile: TgBot.Admin.Api/Dockerfile
      target: final
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - Postgres__Host=postgres
      - Postgres__User=${POSTGRES_USER:-admin}
      - Postgres__Password=${POSTGRES_PASSWORD:-admin}
      - Postgres__Database=${POSTGRES_DB:-tgadmin}
    ports:
      - "127.0.0.1:8000:8080"

  portal:
    build:
      context: ../TgBot.Admin.Portal
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8001:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - portal
      - backend
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

volumes:
  pgdata:
