name: tg-bot-admin

services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ../TgChat.Admin.Api
      dockerfile: Dockerfile
      target: final
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - Mongo__ConnectionString=mongodb://mongo:27017
    ports:
      - "8000:8080"

  portal:
    build:
      context: ../TgBot.Admin.Portal
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000/api
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8001:80"

volumes:
  mongo_data:


